#!/usr/bin/env bash
all=$(git log --pretty=%s $(git merge-base --octopus origin/master)..)
if [ "$?" -ne 0 ]; then
  exit 1
fi
fixups=$(echo "$all" | grep -e "^fixup!")
if [ -z "$fixups" ]; then
  exit 0
fi
echo "$fixups"
exit 1
