#!/usr/bin/env bash
git fetch --quiet origin master
all=$(git log --pretty=%s $(git merge-base --octopus origin/master)..)
if [ "$?" -ne 0 ]; then
  exit 1
fi
RED='\033[0;31m'
NC='\033[0m' # No Color
incorrect=$(echo "$all" | grep -e "^[^A-Z]")
if [ "$incorrect" ]; then
  echo "Commits with an incorrect subject's first character:"
  echo -e "${RED}$incorrect${NC}"
  exit 1
fi
exit 0
