#!/usr/bin/env bash
git fetch --quiet origin master
all=$(git log --pretty=%s $(git merge-base --octopus origin/master)..)
if [ "$?" -ne 0 ]; then
  exit 1
fi
RED='\033[0;31m'
NC='\033[0m' # No Color
longer=$(echo "$all" | grep -e ".\{51,\}")
if [ "$longer" ]; then
  echo "Commits with a subject longer than 50 characters:"
  echo -e "${RED}$longer${NC}"
  exit 1
fi
exit 0
